server.port: 9080

spring:
  application:
    name: research-service
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb1
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults: false    